package databeans;
// Generated Mar 28, 2011 9:22:35 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set productses = new HashSet(0);

    public Categories() {
    }

	
    public Categories(String name) {
        this.name = name;
    }
    public Categories(String name, Set productses) {
       this.name = name;
       this.productses = productses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set productses) {
        this.productses = productses;
    }




}


