package databeans;
// Generated Mar 28, 2011 9:22:35 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer uid;
     private String name;
     private Date dob;
     private String email;
     private String password;
     private String job;
     private Double credit;
     private String interests;
     private Set billses = new HashSet(0);

    public Users() {
    }

	
    public Users(String name, String email, String password) {
        this.name = name;
        this.email = email;
        this.password = password;
    }
    public Users(String name, Date dob, String email, String password, String job, Double credit, String interests, Set billses) {
       this.name = name;
       this.dob = dob;
       this.email = email;
       this.password = password;
       this.job = job;
       this.credit = credit;
       this.interests = interests;
       this.billses = billses;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }
    public Double getCredit() {
        return this.credit;
    }
    
    public void setCredit(Double credit) {
        this.credit = credit;
    }
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }
    public Set getBillses() {
        return this.billses;
    }
    
    public void setBillses(Set billses) {
        this.billses = billses;
    }




}


